### ISSUE TITLE
Cannot enable monitoring for a given hostname in Ops Manager

### ISSUE THREAD

**Issue by TomerFisher** [mongodb/mongocli#813]
**Describe the bug**
When I run the command ```mongocli ops-manager monitoring enable <hostname>``` I get ```Error: PUT http://{OPSMANAGER-HOST}:{PORT}/api/public/v1.0/groups/{PROJECT-ID}/automationConfig: 400 (request "INVALID_ATTRIBUTE") Invalid attribute onlineArchiveModules specified.```

**To Reproduce**
1. Run ```mongocli ops-manager monitoring enable <hostname>```
2. See error

**Expected behavior**
I expected to see the host with the monitoring function enabled in the ops manager.

**Screenshots**
Not possible due to air-locked network.

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
 - MongoCLI version: 1.19.0

**Additional context**
When the host agent **already has** monitoring function enabled and I run the command ```mongocli ops-manager monitoring enable <hostname>```, I get ```Error: monitoring already enabled for '<hostname>'``` which looks like the desired behavior.

**Comment by gssbzn** [comment]
Hi @TomerFisher, I'm guessing this is Ops Manager 4.2? if that's correct sadly mcli support for 4.2 was on a [best effort basis](https://docs.mongodb.com/mongocli/stable/install/compatibility/) given development happened on par with Ops Manager 4.4.

Also at this point Ops Manager 4.2 has reached EOL so we won't be looking into fixing this 

You can also check we currently test this against 4.4 and 5.0 [here](https://github.com/mongodb/mongocli/blob/master/e2e/cloud_manager/agents_test.go)

Further more as an alternative this issue was introduced [here](https://github.com/mongodb/go-client-mongodb-ops-manager/pull/72) so for Ops Manager 4.2 you are probably better off using any CLI version before that change like [v1.8.0](https://docs.mongodb.com/mongocli/stable/release-notes/#mongodb-cli-1.8.0)
