### ISSUE TITLE
'mongocli atlas clusters list' does not appear to work

### ISSUE THREAD

**Issue by SteveH-US** [mongodb/mongocli#883]
**Describe the bug**
Listing processes require "clusterId" which is not listed as a property of a cluster. 

There are two ids provided returned from `mongocli atlas clusters list`
* "id"
* "replicationSpecs.id"

The processes command, `mongocli atlas processes list --clusterId <id>` expects and ID. But using either of these ids returns a 'cluster not found' error. 

If'

**To Reproduce**
1. Run `mongocli atlas processes list --clusterId <id>` using either of the IDs listed above or the cluster name
2. Get CLUSTER_NOT_FOUND 

**Expected behavior**
Please explain what you expected to happen.

The documentation needs to be specific about which ID is requested. If the cluster name is requested, then the "name" property returned from the cluster list command should work. 

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - MongoCLI version 1.20.3
 - Ops Manager Version: Atlas

**Additional context**

**Comment by gssbzn** [comment]
Hi @SteveH-US thanks for this report, this option `--clusterId` is actually unsupported for Atlas and a leftover of a time when it was wrongly documented as supported but we never got to remove it from the code, I've created #887 to remove this option 

Since mongocli is limited to what the public Atlas API provide if you need this option feel free to make a suggestion at https://feedback.mongodb.com/forums/924145-atlas
